name: run my vanilla Cypress tests
on: 
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-slim-chrome99-ff97

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install and build the application
        run: |
          npm install
          npm run build

      - name: run unit tests
        run: |
          npm run test:unit    

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: dist
          if-no-files-found: error
          path: dist

  cypress-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-slim-chrome99-ff97
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          record: false
          start: npm run preview
          wait-on: "http://localhost:5050"
          browser: chrome
          # group: "UI - Chrome"
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cypress-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node16.14.0-slim-chrome99-ff97
      options: --user 1001
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: "UI Tests - Firefox"
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          record: false
          start: npm run preview
          wait-on: "http://localhost:5050"
          browser: firefox
          # group: "UI - Firefox"
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}